version: "3.9"

services:
  client_web:
    build:
      context: ./front
      dockerfile: Dockerfile.browser
    depends_on:
      - client_mobile
      - server
    ports:
      - "8081:8081"
    command: npm start
    volumes:
      - apk:/mobile_app/

  client_mobile:
    build:
      context: ./front
      dockerfile: Dockerfile.android
    volumes:
      - apk:/mobile_app/

  db:
    image: "postgres:10-alpine"
    volumes:
      - "db:/var/lib/postgresql/data"
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: redis:4.0-alpine
    command: redis-server
    ports:
      - 6379
    volumes:
      - "redis:/data"

  sidekiq:
    depends_on:
      - db
      - redis
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bundle exec sidekiq
    volumes:
      - ./backend/:/rails-app
    environment:
      - DATABASE_HOST=db
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1

  server:
    depends_on:
      - db
      - redis
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=db
      - DEVISE_JWT_SECRET_KEY=a6ad96230292468e9bdb2b5d97206d8e6526fb706485e495dfdce612d73f23cfd2bb392c4ef9167688913008db0c6e68cdaf859534829eab5967605e4b357fdf
      - TWITTER_API_PUBLIC=XeKpWymoE8bwWLElXHJVyMD4W
      - TWITTER_API_SECRET=APP_SECRyEvZGxqYCFhqRVQtlxWnusyojL0tVsI2VDNQY3dpTpd0y5ijFJET
      - GOOGLE_API_PUBLIC=786358951542-6embdk4g0midg0odojrc55fq969jrs0a.apps.googleusercontent.com
      - GOOGLE_API_SECRET=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
    volumes:
      - ./backend/:/rails-app
      - bundle:/bundle

volumes:
  redis:
  db:
  apk:
  bundle:
